typography_spectrum: 0.7779892487451434
color:
  brandStrength: 0.11046082549728453
  lightness: 0.7785278768278658
  saturation: 0.7221225567627698
  rhythmicContrast: 0.077303467085585
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.1737057559657842
author:
  name: Rogue Ethic
  url: 'https://rogueethic.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0988daa7-327a-4a9c-82d6-76ca62397a9a.png
name: Rogue Ethic
title: Rogue Ethic
description: 'Mobile, Data, and Service Architecture Solutions'
